/**
 * templateFields — canonical ordered field lists for each statement type.
 *
 * Used as server-side template fallbacks when no company-specific template
 * has been loaded yet. These are production data, not mock data.
 */

export const IS_TEMPLATE_FIELDS: string[] = [
  'Gross Revenue',
  'Net Revenue',
  'Total Revenue',
  'COGS',
  'COGS - Depreciation & Amortization',
  'Gross Profit',
  'Gross Profit Margin %',
  'Sales & Marketing Expenses',
  'Administrative Expenses',
  'Compensation & Benefits Expense',
  'Research & Development',
  'Rent Expense',
  'Management Fee Expense',
  'Other Operating Expenses',
  'Total Operating Expenses',
  'Net Operating Income',
  'Depreciation & Amortization',
  'Loss/(Gain) on Assets, Debt, FX',
  'Non-Operating Expenses',
  'Non-Operating Expenses - Depreciation & Amortization',
  'Interest Expense/(Income)',
  'Other Income',
  'Other Expenses',
  'Total Expense/(Income)',
  'Income (Loss) Before Taxes',
  'Taxes',
  'Net Income (Loss)',
  'EBIT',
  'EBITDA',
  'EBITDA Adjustments',
  'Adjusted EBITDA',
  'Covenant EBITDA',
  'EBITDA Margin %',
  'Adjusted EBITDA Margin %',
  'Covenant EBITDA Margin %',
]

export const BS_TEMPLATE_FIELDS: string[] = [
  'Cash & Cash Equivalents',
  'Short Term Investments',
  'Accounts Receivable',
  'Inventory',
  'Prepaid Expenses',
  'Other Current Assets',
  'Total Current Assets',
  'Property, Plant & Equipment',
  'Accumulated Depreciation',
  'Total Fixed Assets',
  'Other Non-Current Assets',
  'Goodwill & Intangibles',
  'Total Non-Current Assets',
  'Total Assets',
  'Accounts Payable',
  'Short Term Loans',
  'Short Term Capitalized Leases',
  'Short Term Mortgages',
  'Short Term Debt',
  'Accrued Liabilities',
  'Other Current Liabilities',
  'Total Current Liabilities',
  'Long Term Loans',
  'Long Term Capitalized Leases',
  'Long Term Mortgages',
  'Long Term Debt',
  'Deferred Liabilities',
  'Other Non-Current Liabilities',
  'Total Non-Current Liabilities',
  'Total Liabilities',
  'Preferred Stock',
  'Common Stock',
  'Paid in Capital',
  'Other Comprehensive Income',
  'Retained Earnings',
  'Minority Interest',
  'Total Equity',
  'Total Liabilities and Equity',
  'Check',
]
